---
name: WireGuard with custom conf
version: dev
slug: wireguard
description: Fast, modern, secure VPN tunnel
url: https://github.com/avandermeer/addon-wireguard
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
apparmor: true
host_network: true
init: false
ports:
  80/tcp: 80
ports_description:
  80/tcp: WireGuard client status API
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  wg_config_file: "/ssl/wireguard/wg0.conf"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  wg_config_file: str
