---
name: WireGuard with custom conf
version: dev
slug: wireguard
description: Fast, modern, secure VPN tunnel
url: https://github.com/avandermeer/addon-wireguard
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  80/tcp: null
  51820/udp: 51820
ports_description:
  80/tcp: WireGuard peers status API
  51820/udp: "WireGuard: forward this port in your router"
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  wg_config_file: "/ssl/wireguard/wg0.conf"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  wg_config_file: str
